### ISSUE TITLE
Download image does not work in Nova Model view route

### ISSUE THREAD

**Issue by admench** [Silvanite/nova-field-cloudinary#1]
Thanks for a fantastic package. First impressions, this works really well!

![screen shot 2018-10-07 at 20 18 27](https://user-images.githubusercontent.com/672916/46585851-32112d80-ca6e-11e8-9f56-84256264a6e7.png)

Get a failed - server problem - when clicking on this download link.

Can you possibly fix this so the original media is accessible when clicking on this?

**Comment by m2de** [comment]
Hi. Thanks very much. Got to be honest, I never tried the download button, will try and have a look at this as soon as possible.

**Comment by admench** [comment]
No problem, I thought I'd raise it as an issue for the good of this package and for others.

Many thanks

**Comment by sunilvrk** [comment]
i can verify this doesnt work also maybe i missed it but is there a way we can specify which directory to upload to?
