### ISSUE TITLE
Image ID resolving to "/tmp/php......"

### ISSUE THREAD

**Issue by aphofstede** [Silvanite/nova-field-cloudinary#11]
Since recently our image IDs after upload are being set to '/tmp/php<random string>'. Any idea where this is coming from? Bug or misconfig?

**Comment by m2de** [comment]
Hi. Sorry I never saw this issue come in. I haven't seen this happening and would guess at a localised issue to your code/environment. Going to close this as it's pretty old, please let me know if you need it re-opened. Thanks.
