### ISSUE TITLE
Disk [cloudinary] does not have a configured driver.

### ISSUE THREAD

**Issue by mt-gareth** [Silvanite/nova-field-cloudinary#18]
I keep getting this error after setting up things:
//filesystem.php (I also set up my .env)
`
'disks' => [

		'local' => [
			'driver' => 'local',
			'root'   => storage_path( 'app' ),
		],

		'public' => [
			'driver'     => 'local',
			'root'       => storage_path( 'app/public' ),
			'url'        => env( 'APP_URL' ) . '/storage',
			'visibility' => 'public',
		],

		's3' => [
			'driver'   => 's3',
			'key'      => env( 'AWS_ACCESS_KEY_ID' ),
			'secret'   => env( 'AWS_SECRET_ACCESS_KEY' ),
			'region'   => env( 'AWS_DEFAULT_REGION' ),
			'bucket'   => env( 'AWS_BUCKET' ),
			'endpoint' => env( 'AWS_URL' ),
		],

		'cloudinary' => [
			'driver'     => 'cloudinary',
			'api_key'    => env( 'CLOUDINARY_API_KEY' ),
			'api_secret' => env( 'CLOUDINARY_API_SECRET' ),
			'cloud_name' => env( 'CLOUDINARY_CLOUD_NAME' ),
		]

	],
`

//Nova Resource
`
public function fields( Request $request )
	{
		return [
			ID::make()->sortable(),

			CloudinaryImage::make( 'image' ),

			Text::make( 'name' )
				->sortable(),

			BelongsTo::make( 'Episode' ),

			BelongsTo::make( 'Character' )
		];
	}
`

**Comment by mt-gareth** [comment]
Now I'm embarrassed, it was my cache, cleared, and good to go, sorry about that

**Comment by m2de** [comment]
We've all done it 😄 . Glad things are working for you now and thanks for following up and closing the issue.
