### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by Chris-Miracle** [Silvanite/nova-field-cloudinary#23]
Please I am having errors installing the package. Using laravel v8.54
![Screenshot_14](https://user-images.githubusercontent.com/55501479/187099832-aad145d5-bb11-4ba8-886c-c13d1b2781af.png)
4

**Comment by lukebouch** [comment]
@Chris-Miracle It looks like your app uses guzzle 7.4 while this package requires guzzle 6. You will need to downgrade your app to use 6.0 or submit a PR to this repo to upgrade it to 7.4.
