### ISSUE TITLE
Video uploads and raw content

### ISSUE THREAD

**Issue by dorelljames** [Silvanite/nova-field-cloudinary#3]
Thanks for the awesome package. Not so sure whether we have support for Video formats and other files in raw? Thanks

**Comment by m2de** [comment]
Hi @dorelljames . Thanks very much. I have not had a need to implement/try out other formats yet but will be needing this functionality in an upcoming project so it will definitely be reviewed/implemented then.

**Comment by dorelljames** [comment]
Awesome. I'll see if I have spare time to help you speed this up. 👍

**Comment by m2de** [comment]
Forgot to tag this issue. Video support was added some time ago.
